[package]
name = "lang"
version = "0.2.26"
edition = "2024"
license = "MulanPSL-2.0"
repository = "https://github.com/i18n-site/lib.git"
homepage = "https://github.com/i18n-site/lib/tree/dev/lang/gen/rust"
description = "lang"

[features]
nospace = []

[dependencies]
index_of = "0.1.1"
int-enum = "1.2.0"
strum = { version = "0.27.1", features = ["strum_macros", "derive", "phf"] }

# [dependencies]
# int-enum = "1.1.2"
# thiserror = "2.0.12"
#
# [dependencies.bincode]
# version = "2.0.0"
# optional = true
#
# [dependencies.phf]
# version = "0.11.3"
# features = ["macros"]
#
# [dependencies.strum]
# version = "0.27.1"
# features = ["derive"]
#
# [dev-dependencies.aok]
# path = "../aok"
# version = "0.1.17"
#
# [features]
# default = []
# bincode = ["dep:bincode"]