export default {
  alwaysUseImport: true,
  alwaysUseZeroWithoutUnit: true,
  insertBraces: false,
  insertColons: false,
  insertNewLineAroundBlocks: true,
  insertNewLineAroundImports: true,
  insertNewLineAroundOthers: true,
  insertNewLineAroundProperties: true,
  insertSemicolons: false,
  preserveNewLinesBetweenPropertyValues: true,
  reduceMarginAndPaddingValues: true,
  sortProperties: "alphabetical",
  tabStopChar: "  ",
};
