#!/usr/bin/env bun
import { optimize } from "svgo";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { resize } from "./sh/resize.js";

const ROOT = import.meta.dirname,
  SVG_DIR = join(ROOT, "svg"),
  OUT_FILE = join(ROOT, "src/SVG.js"),
  PATTERN_DIR = join(ROOT, "pattern"),
  PATTERN_OUT = join(ROOT, "src/PATTERNS.js"),
  PLUGINS = [
    "preset-default",
    "removeDimensions",
    {
      name: "removeAttributesBySelector",
      params: {
        selector: "svg",
        attributes: ["width", "height", "xmlns"],
      },
    },
  ],
  svg_files = readdirSync(SVG_DIR).filter((f) => f.endsWith(".svg")),
  svg_sizes = new Map(),
  zipSvg = (file) => {
    const path = join(SVG_DIR, file);
    resize(path, file);
    const data = readFileSync(path, "utf8"),
      result = optimize(data, { path, plugins: PLUGINS }),
      view_box = result.data.match(/viewBox="([^"]+)"/)?.[1],
      inner_path = result.data
        .replace(/<svg[^>]*>|<\/svg>/g, "")
        .replace(/stroke="#000"/g, 'stroke="white"')
        .replace(/fill="#000"/g, 'fill="white"');
    if (view_box) {
      const [, , w, h] = view_box.split(/\s+/).map(Number),
        size_key = w + "x" + h;
      if (!svg_sizes.has(size_key)) svg_sizes.set(size_key, []);
      svg_sizes.get(size_key).push(file);
      return [view_box, w, h, inner_path, result.data];
    }
  },
  pattern_files = readdirSync(PATTERN_DIR).filter((f) => f.endsWith(".svg")),
  zipPattern = (file) => {
    const path = join(PATTERN_DIR, file);
    const data = readFileSync(path, "utf8"),
      result = optimize(data, { path, plugins: PLUGINS }),
      view_box = result.data.match(/viewBox="([^"]+)"/)?.[1],
      d = result.data.match(/d="([^"]+)"/)?.[1];
    if (view_box && d) {
      const [, , w] = view_box.split(/\s+/).map(Number);
      return [w, d];
    }
  },
  [svg_data, pattern_data] = await Promise.all([
    Promise.all(svg_files.sort().map(zipSvg)),
    Promise.all(pattern_files.sort().map(zipPattern)),
  ]),
  header =
    "// This file is generated by svgCompress.js. DO NOT EDIT.\n" +
    "const F = (view, w, h, path, raw) => [(x, y, rot, sz, sx, sy, op, grad, mask) => [\n" +
    '  \'<mask id="\' + mask + \'"><g fill="white" stroke="white" stroke-width="10" stroke-linecap="round" stroke-linejoin="round">\' + path + "</g></mask>",\n' +
    '  \'<g transform="translate(\' + x + "," + y + ") rotate(" + rot + "," + (sz / 2) + "," + (sz / 2) + ") skewX(" + sx + ") skewY(" + sy + \')\"><svg viewBox="\' + view + \'" width="\' + sz + \'" height="\' + sz + \'" opacity="\' + op + \'"><rect width="\' + w + \'" height="\' + h + \'" fill="url(#\' + grad + \')" mask="url(#\' + mask + \')"/></svg></g>\'\n' +
    "], raw];\n\nexport default [\n",
  body = svg_data
    .filter(Boolean)
    .map(
      (d) =>
        "  F(\n    " +
        JSON.stringify(d[0]) +
        ",\n    " +
        d[1] +
        ",\n    " +
        d[2] +
        ",\n    " +
        JSON.stringify(d[3]) +
        ",\n    " +
        JSON.stringify(d[4]) +
        "\n  )",
    )
    .join(",\n"),
  footer = "\n];\n";

if (svg_sizes.size > 1) {
  console.warn("\n⚠️  WARN: Inconsistent SVG dimensions detected!");
  for (const [size, list] of svg_sizes) {
    console.warn(
      "   - " +
        size +
        ": " +
        list.length +
        " files (" +
        list.slice(0, 3).join(", ") +
        (list.length > 3 ? "..." : "") +
        ")",
    );
  }
}

writeFileSync(OUT_FILE, header + body + footer);
console.log(svg_data.length + " svg -> " + OUT_FILE);

writeFileSync(
  PATTERN_OUT,
  "// This file is generated by svgCompress.js. DO NOT EDIT.\nexport default " +
    JSON.stringify(pattern_data.filter(Boolean), null, 2) +
    ";\n",
);
console.log(pattern_data.length + " patterns -> " + PATTERN_OUT);
