[package]
name = "_"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
blake3 = { version = "1.5.1", features = ["traits-preview"] }
js-sys = "0.3.69"
wasm-bindgen = "0.2.92"

[profile.release]
opt-level = 's'
lto = true

[build-dependencies]
